name: Custom Test
on: [ workflow_dispatch ]
jobs:
  custom_test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      - name: Set TEST_VAR
        id: set_var
        run: echo ::set-output name=TEST_VAR::$(python src/set_var.py)

      - name: Read TEST_VAR
        run: python src/read_var.py
        env:
          TEST_VAR_INPUT: ${{ steps.set_var.TEST_VAR }}


