name: Deploy
on: [ workflow_dispatch ]
jobs:
  setup:
    runs-on: ubuntu-22.04
    env:
      PROJECT_NAME: test_variable

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: echo "Hello from caller workflow"

  call-steps:
    uses: ./.github/workflows/deploy-steps.yml

  finish-up:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Final message from caller workflow"

