name: Deploy
on: [ workflow_dispatch ]
jobs:
  deploy-heroku:
    runs-on: ubuntu-22.04
    env:
      PROJECT_NAME: test_variable

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: echo "Hello from caller workflow"

